# visit https://github.com/mojombo/jekyll/wiki/Configuration for more settings

paginate: 10 # pagination based on number of posts
paginate_path: "page:num"
exclude: ["README.md"] # files to exclude
pygments: true

title: Eric Clemmons
description: Developer, Husband, Father
author:
  name: Eric Clemmons
  email: eric@smarterspam.com
  github: ericclemmons
  twitter: ericclemmons
  linkedin: ericclemmons
  bio: VP of Software Development @CMN. Dad, open-source addict, musician. Details matter.
  email_md5: b6ffb4f3fe821e31f69923630dfdebc5


permalink: /:categories/:title
rss_path: feed.xml
categories_path: categories.html
tags_path: tags.html
excerpt_separator: ---

# BASE_PATH: http://ericclemmons.github.io

# All links will be namespaced by BASE_PATH if defined.
# Links in your website should always be prefixed with {{ site.BASE_PATH }}
# Do not put a "/" at the end of the url.
#
# CNAME (http://yourcustomdomain.com)
#   DO NOT SET BASE_PATH JUST LEAVE IT BLANK
#   (urls will be prefixed with "/" and work relatively)
#
# GitHub Pages (http://username.github.io)
#   DO NOT SET BASE_PATH JUST LEAVE IT BLANK
#   (urls will be prefixed with "/" and work relatively)
#
# GitHub Project Pages (http://username.github.io/project-name)
#  A GitHub Project site exists in the `gh-pages` branch of one of your repositories.
#  REQUIRED! Set BASE_PATH to "http://username.github.io/project-name"
