title:            Eric Clemmons
description:      "VP of Software Development @CMN. Dad, open-source addict, musician. Details matter."
logo:             http://www.gravatar.com/avatar/b6ffb4f3fe821e31f69923630dfdebc5.png
disqus_shortname: ericclemmons
# Assign a default image for your site's header and footer
default_bg:       breck.jpg
search:           true
share:            true
# Read Time is a calculator tp provide post read-time based on word count. Usage is recommended.
readtime:         true
# Turn on or off the fin animations in the header and footer
animated_fins:	  true
# Specify the fin color in RGB value
fin_color:        "0,0,0"
# Change url to your domain. Leave localhost server or blank when working locally.
# or use the hint from http://jekyllrb.com/docs/github-pages/ to keep this the same
# whether working locally or remotely. Start Jekyll with: jekyll serve --baseurl ''
baseurl:          ''

# Owner/author information
owner:
  name:           Eric Clemmons
  avatar:         http://www.gravatar.com/avatar/b6ffb4f3fe821e31f69923630dfdebc5.png
  email:          eric@smarterspam.com
  description:    "VP of Software Development @CMN. Dad, open-source addict, musician. Details matter."
  twitter:        ericclemmons
  facebook:       ericclemmons
  github:         ericclemmons
  stackexchange:  https://stackexchange.com/users/66169/eric
  linkedin:       ericclemmons
  google_plus:    http://google.com/+EricClemmons

# Analytics and webmaster tools stuff goes here
google_analytics:   UA-49806707-1
google_verify:
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Links to include in footer navigation
# For external links add external: true
links:
  - title: Home
    url: /
    external: false
    icon: home
  - title: Categories
    url: /categories
  - title: Tags
    url: /tags

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:    America/Chicago
future:      true
pygments:    true
markdown:    kramdown
paginate:    10
paginate_path: "page:num"

# https://github.com/mojombo/jekyll/wiki/Permalinks
permalink:   /:categories/:title
excerpt_separator: ---

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: false

  coderay:
    coderay_line_numbers:
    coderay_line_numbers_start: 1
    coderay_tab_width: 4
    coderay_bold_every: 10
    coderay_css: class

include: [".htaccess"]
exclude: ["lib", "config.rb", "Gemfile", "Capfile", "Gemfile.lock", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules"]
