imports:
    - { resource: parameters.yml }

framework:
    secret:          %secret%
    charset:         UTF-8
    router:          { resource: "%kernel.root_dir%/config/routing.yml" }
    form:            true
    csrf_protection: true
    validation:      { enable_annotations: true }
    templating:      { engines: ['twig'], assets_version:  %version% }
    default_locale:  %locale%
    session:
        auto_start:  false

# Twig Configuration
twig:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%

# Assetic Configuration
assetic:
    debug:          %kernel.debug%
    use_controller: false
    bundles:
        - EricClemmonsSiteBundle
    filters:
        cssrewrite: ~
        less:
            node: /usr/local/bin/node
            node_paths: [/usr/local/lib/node_modules]
        yui_js:
           jar: %kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar
        yui_css:
           jar: %kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar

# Static content Configuration
eric_clemmons_static: ~
